# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo_esp',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='articulos_esp',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidoapp.Articulo'),
        ),
        migrations.DeleteModel(
            name='Articulo_esp',
        ),
    ]
