# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidoapp', '0002_auto_20170303_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='ADMISION',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='AUX_ASEO',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='BRONCOPULMONAR',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='CARDIOLOGIA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='CLINICA_CURACION',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='CURACION_AVANZADA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='DERMATOLOGIA_FOTOTERAPIA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='DIABETES',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='DRA_CASTELLON',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='EDA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='EEG',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ESTACION_ENF_CONSULTA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ESTACION_ENF_PROCED',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='FIBROBRONCOSCOPIA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='FONOAUDIOLOGIA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='LUMBAR',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='NEUROLOGIA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='OFTAMOLOGIA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='OTORRINO',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='PAT_MAMARIA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='POLI_TACO',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='PREPARACION_A',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='PREPARACION_B',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='PROG_HEPATITIS',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='PROG_VIH',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='P_CX_MENOR',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='RECUPERACION',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='SALA_DAN',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='SALA_INFORMES_CONS',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='SALA_INFORMES_POC',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='SECRETARIAS_CAE',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='TMT',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='UROLOGIA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
