# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidoapp', '0004_auto_20170308_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='estadistica',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
