# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidoapp', '0007_auto_20170315_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(blank=True),
        ),
    ]
