# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidoapp', '0008_auto_20170317_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido_ex', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_entrega_ex', models.DateTimeField()),
                ('cantidad_ex', models.IntegerField(blank=True, default=0)),
                ('estado_ex', models.CharField(blank=True, default='pendiente', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pendiente',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pedido_extra',
            name='articulo_ex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidoapp.Articulo'),
        ),
        migrations.AddField(
            model_name='pedido_extra',
            name='especialidad_ex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidoapp.Especialidad'),
        ),
    ]
