# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidoapp', '0012_pedido_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='acceso',
        ),
        migrations.AddField(
            model_name='especialidad',
            name='acceso',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
