# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidoapp', '0014_auto_20170327_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(null=True),
        ),
    ]
