# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidoapp', '0017_auto_20170328_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
