# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidoapp', '0018_auto_20170329_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad_update',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
