# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidoapp', '0019_pedido_cantidad_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_update',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
